apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-netflow-collector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-netflow
  template:
    metadata:
      labels:
        app: fluentd-netflow
    spec:
      containers:
        - name: fluentd
          image: quay.io/mmaciasl/fluentd-os:latest
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-netflow-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: fluentd-netflow
  ports:
    - port: 2055
      targetPort: 2055
      nodePort: 32055
