apiVersion: v1
kind: Namespace
metadata:
  name: flows
  labels:
    name: flows
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-netflow-collector
  namespace: flows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: quay.io/mmaciasl/fluentd-os:latest
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-netflow-service
  namespace: flows
spec:
  type: NodePort
  selector:
    app: fluentd
  ports:
    - port: 2055
      targetPort: 2055
      nodePort: 32055
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendistro
  namespace: flows
  labels:
    app: opendistro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendistro
  template:
    metadata:
      labels:
        app: opendistro
    spec:
      containers:
        - name: opendistro
          image: amazon/opendistro-for-elasticsearch:1.13.2
          env:
            - name: discovery.type
              value: "single-node"
          ports:
            - containerPort: 9200
        - name: opendistro-kibana
          image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: https://localhost:9200
            - name: ELASTICSEARCH_HOSTS
              value: https://localhost:9200
